worker_processes  1;

events { worker_connections 1024; }

http {
  # 512 МБ кеш, ключи в памяти 10 МБ
  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cdn_cache:10m max_size=512m inactive=1h use_temp_path=off;

  # удобный лог
  log_format main '$remote_addr - $request "$status" $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" cache:$upstream_cache_status';
  access_log /dev/stdout main;

  server {
    listen 80;

    # все файлы ведём на MinIO bucket "reports"
    location /reports/ {
   	  proxy_pass http://minio:9000;
      proxy_set_header Host $host;

      # кеширование
      proxy_cache cdn_cache;
      proxy_cache_valid 200 206 301 302 10m;   # 10 минут — достаточно для стенда
      proxy_cache_lock on;
      proxy_ignore_headers Set-Cookie;
      add_header X-Cache $upstream_cache_status always;

      # Гарантируем корректные типы
      types {
        text/csv                              csv;
        application/json                      json;
        application/pdf                       pdf;
        text/plain                            txt;
      }
      default_type application/octet-stream;
    }

    # health
    location = /healthz { return 200 'ok'; add_header Content-Type text/plain; }
  }
}
