services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "29092:29092"

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8090:8080"   


  crm_db:
    image: postgres:16-alpine
    container_name: crm_db
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c wal_keep_size=256
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d

  connect:
    image: quay.io/debezium/connect:2.7.4.Final   
    container_name: connect
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    ports:
      - "8085:8083"


  register-connector:
    image: curlimages/curl:8.7.1
    container_name: register-connector
    depends_on:
      - connect
      - crm_db
      - kafka
    volumes:
      - ./debezium/connector.json:/connector.json:ro
    entrypoint: ["/bin/sh","-c"]
    command: >
      "echo 'Waiting for Kafka Connect...';
       until curl -s http://connect:8083/connectors >/dev/null; do sleep 2; done;
       curl -s -X PUT -H 'Content-Type: application/json'
         --data @/connector.json
         http://connect:8083/connectors/crm-connector/config;
       echo 'Connector registered';
       tail -f /dev/null"

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "8123:8123"     
      - "9005:9000"   
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: ch
      CLICKHOUSE_PASSWORD: ch
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 0
    volumes:
      - ./clickhouse/init:/docker-entrypoint-initdb.d
      - ch_data:/var/lib/clickhouse


volumes:
  ch_data:
